SELECT
  spec.RowId AS RowId,
  spec.inboundRequestId as InboundRequestId,
  res.RequestStatusId AS RequestStatusId,
  res.ModifiedResultFlag AS ModifiedResultFlag,
  spec.CustomerBarcode AS CustomerBarcode,
  spec.LastName AS LastName,
  spec.FirstName AS FirstName,
  spec.MiddleName AS MiddleName,
  spec.Initials AS Initials,
  spec.GenderId AS GenderId,
  spec.BirthDate AS BirthDate,
  spec.DODId AS DODId,
  spec.SSN AS SSN,
  spec.FMPId AS FMPId,
  spec.DutyCodeId AS DutyCodeid,
  spec.TestingSourceId AS TestingSourceId,
  spec.DrawDate as DrawDate,
  res.Received AS Received,
  res.Completed AS Completed,
  res.SampleIntegrity AS SampleIntegrity,
  res.TestResult AS TestResult,
  res.CustomerCode AS CustomerCode,
  res.ReportFileName as ReportFileName
FROM hdrl.InboundSpecimen spec LEFT JOIN hdrl.SpecimenResult res ON spec.RowId = res.specimenId;